import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { SecureStore } from '../utils/secureStore';

export type Language = 'es' | 'en' | 'it';

// Traducciones completas de la app
export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  es: {
    // General
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    confirm: 'Confirmar',
    back: 'Volver',
    next: 'Siguiente',
    previous: 'Anterior',
    done: 'Hecho',
    error: 'Error',
    success: 'Éxito',
    close: 'Cerrar',
    start: 'Iniciar',
    stop: 'Detener',
    retry: 'Reintentar',
    
    // Auth/Registration
    welcomeBack: 'Bienvenido de vuelta',
    createAccount: 'Crear cuenta',
    loginToContinue: 'Inicia sesión para continuar',
    registerToStart: 'Regístrate para comenzar',
    nameRequired: 'El nombre es requerido',
    invalidAge: 'Edad inválida',
    invalidWeight: 'Peso inválido',
    myPets: 'Mis mascotas',
    epilepsyDiary: 'Diario de epilepsia',
    demoDataLabel: 'DATOS SIMULADOS',
    sensorNoData: 'No se están recibiendo datos del sensor.',
    noMeasurementsYet: 'Todavía no hay mediciones.',
    demoMode: 'Modo demostración',
    exitDemoMode: 'Salir de demo',
    notes: 'Notas',
    thisMonth: 'Este mes',
    epilepsySubtitle: 'Para perros y gatos con epilepsia: registra las crisis y compártelas con tu veterinario',
    epilepsyInfo: 'Registra cada crisis de {name} con fecha, duración e intensidad. Este historial ayuda a tu veterinario a ajustar el tratamiento.',
    registerSeizure: 'Registrar crisis',
    totalSeizures: 'Crisis totales',
    lastSeizure: 'Última crisis',
    noSeizures: 'Sin crisis registradas. ¡Ojalá siga así! Registra aquí cualquier episodio.',
    seizureDate: 'Fecha',
    durationMinutes: 'Duración (minutos)',
    severity: 'Intensidad',
    sevMild: 'Leve',
    sevModerate: 'Moderada',
    sevSevere: 'Fuerte',
    trigger: 'Desencadenante',
    triggerPlaceholder: 'Ej: estrés, calor, luces...',
    notesPlaceholder: 'Describe lo que observaste...',
    optional: 'opcional',
    invalidDate: 'Fecha inválida (usa YYYY-MM-DD)',
    seizureSaveError: 'No se pudo guardar la crisis',
    addPet: 'Añadir mascota',
    addPetSubtitle: 'Cuéntanos sobre tu nueva mascota',
    savePet: 'Guardar mascota',
    petAdded: 'Mascota añadida correctamente',
    petAddError: 'No se pudo guardar la mascota',
    dogNamePlaceholder: '¿Cómo se llama?',
    dogSex: 'Sexo (opcional)',
    male: 'Macho',
    female: 'Hembra',
    emailRequired: 'El email es requerido',
    invalidEmail: 'Email inválido',
    passwordRequired: 'La contraseña es requerida',
    minCharacters: 'Mínimo 6 caracteres',
    genericError: 'Ha ocurrido un error. Inténtalo de nuevo.',
    googleLoginError: 'No se pudo iniciar sesión con Google',
    loginButton: 'Iniciar Sesión',
    createAccountButton: 'Crear Cuenta',
    orContinueWith: 'o continúa con',
    continueWithGoogle: 'Continuar con Google',
    noAccount: '¿No tienes cuenta? ',
    haveAccount: '¿Ya tienes cuenta? ',
    register: 'Regístrate',
    login: 'Inicia sesión',
    yourName: 'Tu nombre',
    email: 'Email',
    password: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    recoverPassword: 'Recuperar contraseña',
    enterEmailToRecover: 'Introduce tu email para recibir un código de recuperación',
    sendCode: 'Enviar código',
    recoveryCode: 'Código de recuperación',
    yourCodeIs: 'Tu código es',
    codeExpiresIn: 'Expira en 10 minutos',
    enterCode: 'Introduce el código de 6 dígitos',
    enterCodeAndPassword: 'Introduce el código y tu nueva contraseña',
    code: 'Código',
    newPassword: 'Nueva contraseña',
    changePassword: 'Cambiar contraseña',
    resendCode: 'Reenviar código',
    passwordUpdated: 'Contraseña actualizada correctamente',
    
    // Navigation
    home: 'Inicio',
    health: 'Salud',
    education: 'Educación',
    chat: 'Chat',
    profile: 'Perfil',
    
    // Home Screen
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    positiveEducation: 'Educación en Positivo',
    todaySession: 'Sesión de Hoy',
    homeBannerTitle: 'Analiza y entiende la salud de tu animal',
    homeBannerSubtitle: 'Sube una foto, un documento o describe un síntoma y obtén una explicación clara',
    homeBannerCta: 'Empezar análisis',
    yourProgress: 'Tu Progreso',
    quickAccess: 'Accesos rápidos',
    healthActivity: 'Actividad de salud',
    lastConsultation: 'Ultima consulta IA',
    lastMedicalEvent: 'Ultimo evento medico',
    emotionalState: 'Estado emocional',
    noConsultationsYet: 'Sin consultas aun',
    noEventsYet: 'Sin eventos registrados',
    notRegisteredToday: 'Sin registrar hoy',
    today: 'Hoy',
    yesterday: 'Ayer',
    daysAgo: 'Hace {n} dias',
    emotionHappy: 'Feliz',
    emotionCalm: 'Tranquilo',
    emotionWorried: 'Preocupado',
    emotionSad: 'Triste',
    emotionStressed: 'Estresado',
    exerciseLibrary: 'Biblioteca de Ejercicios',
    viewAll: 'Ver todo',
    greatJob: '¡Gran trabajo! Has ganado',
    bonesToday: 'huesos hoy',
    viewRewards: 'Ver premios',
    level: 'Nivel',
    exercises: 'Ejercicios',
    practice: 'Práctica',
    bones: 'Huesos',
    almostLevel: '¡Casi llegas al Nivel',
    days: 'Días',
    nextGoal: 'Siguiente',
    haveQuestions: '¿Tienes dudas?',
    askHani: 'Pregúntale a Heimdall, experto en bienestar canino',
    guardianChat: 'Tu guardián',
    thePerfectCall: 'La Llamada Perfecta',
    intermediate: 'Intermedio',
    highPriority: 'PRIORIDAD ALTA',
    min: 'min',
    explorerLevel: 'Explorador Canino',
    basicSignals: 'Señales Básicas',
    sitDownStay: 'Sentado, Tumbado, Quieto',
    impulseControl: 'Control de Impulsos',
    waitLeaveRelease: 'Espera, Deja, Suelta',
    socialization: 'Socialización',
    dogsPeopleEnvironments: 'Perros, Personas, Entornos',
    
    // Quick Access
    vest: 'Chaleco',
    walks: 'Paseos',
    uploadAnalysis: 'Subir análisis',
    describeSymptom: 'Describir síntoma',
    history: 'Historial',
    academy: 'Academia',
    pro: 'PRO',
    
    // Health Screen
    health360: 'Salud 360°',
    realTimeMonitoring: 'Monitorización en tiempo real',
    heartRate: 'Frecuencia Cardíaca',
    temperature: 'Temperatura',
    activity: 'Actividad',
    stress: 'Estrés',
    bpm: 'lpm',
    high: 'Alta',
    medium: 'Media',
    low: 'Bajo',
    normal: 'Normal',
    connectVest: 'Conectar Chaleco',
    vestConnected: 'Chaleco conectado',
    vestDisconnected: 'Chaleco desconectado',
    medicalHistory: 'Historial Médico',
    viewMedicalHistory: 'Ver historial completo',
    lastVaccine: 'Última vacuna',
    lastDeworming: 'Última desparasitación',
    lastVetVisit: 'Última visita veterinaria',
    biometrics: 'Biométricos',
    vitalSigns: 'Signos Vitales',
    activityLevel: 'Nivel de Actividad',
    stressLevel: 'Nivel de Estrés',
    sleeping: 'Durmiendo',
    resting: 'Descansando',
    active: 'Activo',
    veryActive: 'Muy Activo',
    calm: 'Tranquilo',
    relaxed: 'Relajado',
    alert: 'Alerta',
    anxious: 'Ansioso',
    
    // Education Screen
    heimdallAcademy: 'Academia Heimdall',
    heimdallBones: 'Huesos Heimdall',
    todaySessionTitle: 'Sesión de Hoy',
    guidedPrograms: 'Programas Guiados',
    basicEducation: 'Educación Básica',
    solidFoundations: 'Fundamentos sólidos',
    calmControl: 'Calma y Control',
    emotionalManagement: 'Gestión emocional',
    canineWorld: 'Mundo Canino',
    positiveSocialization: 'Socialización positiva',
    puppyStart: 'Inicio Cachorro',
    firstSteps: 'Primeros pasos',
    basic: 'Básico',
    emotional: 'Emocional',
    social: 'Social',
    puppies: 'Cachorros',
    recommendedGames: 'Juegos Recomendados',
    mentalPuzzle: 'Puzzle Mental',
    tugOfWar: 'Tira y Afloja',
    difficulty: 'Dificultad',
    bond: 'Vínculo',
    lessons: 'Lecciones',
    
    // Chat Screen
    chatWithHani: 'Chat con Hani',
    askAnything: 'Pregunta lo que quieras sobre tu perro',
    typeMessage: 'Escribe tu mensaje...',
    send: 'Enviar',
    haniGreeting: '¡Hola! Soy Hani, tu asistente de educación canina. ¿En qué puedo ayudarte hoy?',
    thinking: 'Pensando...',
    analyzing: 'Analizando',
    whyDogBarks: '¿Por qué mi perro ladra tanto?',
    rainyDayGames: 'Juegos para días de lluvia',
    howMuchToEat: '¿Cuánto debe comer mi perro?',
    trySaying: 'Prueba preguntar:',
    
    // Profile Screen
    myPack: 'Mi manada',
    invite: 'Invitar',
    mainOwner: 'Dueño principal',
    clinicalFile: 'Ficha Clínica',
    country: 'País',
    vet: 'Veterinario',
    allergies: 'Alergias',
    notAssigned: 'Sin asignar',
    noneRegistered: 'Ninguna registrada',
    editClinicalFile: 'Editar ficha clínica',
    goToPro: 'Pásate a PRO',
    activatePro: 'Activar PRO',
    settings: 'Ajustes',
    notifications: 'Notificaciones',
    privacy: 'Privacidad y datos',
    help: 'Ayuda',

    // Privacy screen
    privacyTitle: 'Privacidad y Datos',
    dataCollection: 'Datos que recopilamos',
    dataCollectionDesc: 'Heimdall recopila datos basicos de tu perfil y el de tu perro para personalizar la experiencia. Esto incluye nombre, raza, edad, peso y datos de entrenamiento.',
    dataStorage: 'Almacenamiento seguro',
    dataStorageDesc: 'Tus datos se almacenan de forma segura en servidores encriptados. Utilizamos Supabase con cifrado AES-256 en reposo.',
    dataSharing: 'Compartimos tus datos?',
    dataSharingDesc: 'No vendemos ni compartimos tus datos personales con terceros. Solo usamos la informacion para mejorar tu experiencia en la app.',
    aiDataUsage: 'Uso de datos en la IA',
    aiDataUsageDesc: 'Las conversaciones con Hani se procesan mediante OpenAI. No se almacenan en los servidores de IA despues de procesarse.',
    deleteAccount: 'Eliminar mi cuenta',
    deleteAccountDesc: 'Al eliminar tu cuenta se borraran permanentemente todos tus datos, incluyendo perfiles, historial y progreso.',
    deleteAccountConfirm: 'Esta accion es irreversible. Todos tus datos seran eliminados permanentemente.',
    termsOfService: 'Terminos de servicio',
    privacyPolicy: 'Politica de privacidad',
    lastUpdated: 'Ultima actualizacion',

    // Help screen
    helpTitle: 'Centro de Ayuda',
    faq: 'Preguntas Frecuentes',
    faqTraining: 'Como funciona el entrenamiento?',
    faqTrainingAnswer: 'Heimdall ofrece programas de entrenamiento guiados paso a paso. Completa ejercicios, gana huesos y sube de nivel mientras tu perro aprende.',
    faqPro: 'Que incluye Heimdall PRO?',
    faqProAnswer: 'PRO desbloquea analisis de video IA, informes veterinarios, backup en la nube y funciones avanzadas de analisis.',
    faqBluetooth: 'Como conecto el chaleco?',
    faqBluetoothAnswer: 'Activa el Bluetooth, ve a la seccion del chaleco y pulsa buscar dispositivos. Asegurate de que el chaleco ESP32 esta encendido.',
    faqData: 'Mis datos estan seguros?',
    faqDataAnswer: 'Si. Usamos cifrado de extremo a extremo y nunca compartimos tus datos con terceros.',
    contactSupport: 'Contactar soporte',
    contactEmail: 'soporte@heimdall-hani.app',
    reportBug: 'Reportar un error',
    rateApp: 'Valorar la app',
    rateAppDesc: 'Tu opinion nos ayuda a mejorar',
    appVersion: 'Version de la app',

    // PRO screen
    proTitle: 'Heimdall PRO',
    proSubtitle: 'Desbloquea todo el potencial de Heimdall',
    alreadyPro: 'Ya eres PRO!',
    enjoyPro: 'Disfruta de todas las funciones premium de Heimdall',
    backToHome: 'Volver al inicio',
    proFeatureVideo: 'Analisis de Video IA',
    proFeatureVideoDesc: 'Sube videos de tu perro y recibe analisis de comportamiento',
    proFeatureReports: 'Informes Veterinarios',
    proFeatureReportsDesc: 'Genera informes completos para compartir con tu veterinario',
    proFeatureChat: 'Chat Ilimitado con Hani',
    proFeatureChatDesc: 'Sin limite de mensajes con tu asistente IA',
    proFeatureAnalytics: 'Analisis Avanzado',
    proFeatureAnalyticsDesc: 'Graficos detallados de salud y comportamiento',
    proFeatureCloud: 'Backup en la Nube',
    proFeatureCloudDesc: 'Todos tus datos seguros y sincronizados',
    proFeaturePack: 'Manada Familiar',
    proFeaturePackDesc: 'Invita hasta 5 miembros a gestionar tu perro',
    allProIncludes: 'Todo lo que incluye PRO',
    choosePlan: 'Elige tu plan',
    monthly: 'Mensual',
    annual: 'Anual',
    mostPopular: 'MAS POPULAR',
    savingsPercent: 'Ahorra 32%',
    activateProNow: 'Activar PRO Ahora',
    processing: 'Procesando...',
    restorePurchases: 'Restaurar compras',
    cancelAnytime: 'Cancela cuando quieras. Al suscribirte aceptas los',
    guarantee7days: 'Garantia de 7 dias',
    guaranteeDesc: 'Si no estas satisfecho, te devolvemos el dinero sin preguntas.',
    securePayment: 'Pago seguro con',
    loadingPlans: 'Cargando planes...',
    language: 'Idioma',
    logout: 'Cerrar sesión',
    logoutConfirm: '¿Estás seguro de que quieres cerrar sesión?',
    age: 'Edad',
    weight: 'Peso',
    breed: 'Raza',
    editProfile: 'Editar Perfil',
    name: 'Nombre',
    changePhoto: 'Cambiar foto',
    selectLanguage: 'Seleccionar Idioma',
    spanish: 'Español',
    english: 'English',
    italian: 'Italiano',
    years: 'años',
    months: 'meses',
    and: 'y',
    chip: 'Chip',
    videoAnalysis: 'Análisis de video',
    vetReports: 'Informes veterinarios',
    unlimitedChat: 'Chat ilimitado con Hani',
    editDogProfile: 'Editar perfil de tu perro',
    dogName: 'Nombre del perro',
    dogAge: 'Edad (meses)',
    dogWeight: 'Peso (kg)',
    dogBreed: 'Raza',
    chipId: 'Número de chip',
    
    // Lessons
    step: 'Paso',
    of: 'de',
    complete: 'Completar',
    lessonCompleted: '¡Lección Completada!',
    practicalExercise: 'Tu Ejercicio Práctico',
    backToEducation: 'Volver a Educación',
    proTip: 'Consejo Pro',
    whatYouWillLearn: 'Lo que aprenderás:',
    commonMistakes: 'Errores Comunes a Evitar:',
    
    // Gamification
    myRewards: 'Mis Recompensas',
    achievements: 'Logros',
    streak: 'Racha',
    totalBones: 'Huesos totales',
    levelUp: '¡Subiste al Nivel',
    newAchievement: '¡Nuevo Logro!',
    noAchievements: 'Completa lecciones para desbloquear logros',
    inviteSent: '¡Invitación enviada! +5 huesos',
    
    // Exercises
    completed: 'completados',
    instructions: 'Instrucciones:',
    repetitions: 'repeticiones',
    exercisesCompleted: '¡Ejercicios Completados!',
    description: 'Descripción',
    benefits: 'Beneficios',
    materials: 'Materiales necesarios',
    
    // Routes
    routes: 'Rutas',
    startRoute: 'Iniciar Ruta',
    stopRoute: 'Detener',
    saveRoute: 'Guardar Ruta',
    routeHistory: 'Historial de Rutas',
    noRoutes: 'Aún no tienes rutas guardadas',
    routeSaved: 'Ruta guardada',
    distance: 'Distancia',
    duration: 'Duración',
    tracking: 'Rastreando',
    walkWithDog: 'Pasea con tu perro',
    startWalk: 'Iniciar paseo',
    endWalk: 'Terminar paseo',
    walkCompleted: '¡Paseo completado!',
    bonesEarned: 'huesos ganados',
    steps: 'Pasos',
    points: 'Puntos',
    locationPermission: 'Permiso de ubicación',
    locationPermissionDesc: 'Necesitamos acceso a tu ubicación para rastrear las rutas de paseo con tu perro',
    grantPermission: 'Conceder permiso',
    permissionDenied: 'Permiso denegado',
    permissionDeniedDesc: 'Activa la ubicación en los ajustes de tu dispositivo',
    hikingTrails: 'Rutas de senderismo',
    hikingTrailsDesc: 'Rutas recomendadas para pasear',
    easy: 'Fácil',
    moderate: 'Moderada',
    hard: 'Difícil',
    dogFriendly: 'Dog-friendly',
    pedometerActive: 'Podómetro activo',
    todaySteps: 'Pasos hoy',
    liveTracking: 'Seguimiento en vivo',
    stopAndSave: 'Detener y Guardar',
    startWalkWithDog: 'Paseo con',
    savedRoutes: 'Rutas guardadas',
    noRoutesHint: 'Inicia un paseo para guardar tu primera ruta',
    
    // PRO
    proBenefits: 'Beneficios PRO',
    monthlyPlan: 'Mensual',
    yearlyPlan: 'Anual',
    mostPopular: 'MÁS POPULAR',
    savingsPercent: 'Ahorra',
    activateNow: 'Activar PRO Ahora',
    restorePurchases: 'Restaurar compras',
    guarantee: 'Garantía de 7 días',
    guaranteeText: 'Si no estás satisfecho, te devolvemos el dinero sin preguntas.',
    alreadyPro: '¡Ya eres PRO!',
    enjoyPremium: 'Disfruta de todas las funciones premium de Heimdall',
    unlockPotential: 'Desbloquea todo el potencial de Heimdall',
    everythingIncluded: 'Todo lo que incluye PRO',
    choosePlan: 'Elige tu plan',
    securePayment: 'Pago seguro con',
    month: 'mes',
    year: 'año',
    
    // Medical History
    addEvent: 'Añadir evento',
    vaccines: 'Vacunas',
    deworming: 'Desparasitación',
    vetVisits: 'Visitas veterinarias',
    medications: 'Medicamentos',
    surgeries: 'Cirugías',
    other: 'Otros',
    noEvents: 'No hay eventos registrados',
    eventAdded: 'Evento añadido',
    eventDeleted: 'Evento eliminado',
    eventType: 'Tipo de evento',
    eventDate: 'Fecha',
    eventDescription: 'Descripción',
    
    // Vest/Bluetooth
    smartVest: 'Chaleco Inteligente',
    connectDevice: 'Conectar dispositivo',
    disconnectDevice: 'Desconectar',
    searching: 'Buscando...',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    batteryLevel: 'Nivel de batería',
    lastSync: 'Última sincronización',
    syncNow: 'Sincronizar ahora',
    deviceNotFound: 'Dispositivo no encontrado',
    bluetoothOff: 'Bluetooth desactivado',
    enableBluetooth: 'Activa Bluetooth para continuar',
    simulatorMode: 'Modo Simulador',
    simulatorDescription: 'Usando datos simulados para demostración',
    
    // Onboarding
    nowWatching: 'Ahora Heimdall vigila a',
    yourDog: 'tu perro',
    configuredDescription: 'Hemos configurado todo para que puedas monitorear la salud y bienestar de tu compañero peludo.',
    personalizedAI: 'Asistente IA personalizado',
    goToHome: 'Ir al inicio',
    
    // Google Wallet
    digitalIdCard: 'Tarjeta de identificación digital',
    addToGoogleWallet: 'Añadir a Google Wallet',
    walletCardDescription: 'Lleva la identificación de tu perro siempre contigo en Google Wallet',
    
    // Bluetooth/ESP32
    scanForDevices: 'Buscar dispositivos',
    stopScanning: 'Detener búsqueda',
    noDevicesFound: 'No se encontraron dispositivos',
    connectingTo: 'Conectando a',
    esp32Device: 'Dispositivo ESP32',
    heimdallVest: 'Chaleco Heimdall',
    signalStrength: 'Intensidad de señal',
    availableDevices: 'Dispositivos disponibles',
    howToConnect: '¿Cómo conectar?',
    turnOnVest: 'Enciende el chaleco Heimdall',
    pressSearchButton: 'Pulsa "Buscar dispositivos"',
    selectDevice: 'Selecciona tu chaleco de la lista',
    bleNotAvailableInExpoGo: 'Bluetooth BLE no está disponible en Expo Go. Para conectar con el chaleco real, necesitas crear un "Development Build" de la app. Por ahora, usa el "Simulador" para probar.',
    useSimulator: 'Usar simulador',
    realDevice: 'Dispositivo real',
    disconnectConfirm: '¿Estás seguro de que quieres desconectar el chaleco?',
    
    // Leaderboard
    leaderboard: 'Ranking',
    leaderboardTitle: 'Ranking de la Manada',
    topTrainers: 'Mejores Entrenadores',
    yourPosition: 'Tu posición',
    noRankYet: 'Completa lecciones para aparecer',
    rank: 'Puesto',
    viewLeaderboard: 'Ver ranking',
    
    // Weekly Summary
    weeklyProgress: 'Progreso Semanal',
    thisWeek: 'Esta semana',
    bonesThisWeek: 'Huesos',
    exercisesThisWeek: 'Actividades',
    xpThisWeek: 'XP ganado',
    streakActive: 'Racha activa',
    keepItUp: '¡Sigue así!',
    startTraining: '¡Empieza a entrenar esta semana!',
    weeklyGoal: 'Meta semanal',
    daysActive: 'Días activo',
    darkMode: 'Modo oscuro',
    lightMode: 'Modo claro',
    theme: 'Tema',
    appearance: 'Apariencia',

    // Health vest banner
    vestComingSoon: 'Proximamente con el Pack Chaleco',
    vestComingSoonDesc: 'Las metricas que ves son de ejemplo. Conecta el chaleco Heimdall ESP32 para monitorizar a tu perro en tiempo real.',
    vestGetPack: 'Descubrir Pack Chaleco',
    demoData: 'Datos de ejemplo',
    howDoYouFeel: '¿Cómo os sentís hoy?',
    startEmotionDiary: 'Empezar diario emocional',
    todayYouFeel: 'Hoy te sientes...',
    addNotePlaceholder: 'Añade una nota (opcional)...',
    saving: 'Guardando...',
    update: 'Actualizar',
    weeklyInsight: 'Insight Semanal',
    analyzingWeek: 'Analizando tu semana...',
    dominantEmotion: 'Emoción predominante:',
    diaryEmpty: 'Empieza tu diario registrando cómo os sentís hoy. Heimdall analizará tus emociones cada semana.',
    diaryError: 'No se pudo guardar la entrada',
    emotionHappy: 'Feliz',
    emotionCalm: 'Tranquilo',
    emotionWorried: 'Preocupado',
    emotionSad: 'Triste',
    emotionStressed: 'Estresado',
    // What does Heimdall do
    whatDoesHeimdall: 'Que hace Heimdall?',
    heimdallFeature1: 'Entiende la salud de tu animal',
    heimdallFeature2: 'Detecta riesgos a tiempo',
    heimdallFeature3: 'Toma decisiones con claridad',
  },
  en: {
    // General
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    done: 'Done',
    error: 'Error',
    success: 'Success',
    close: 'Close',
    start: 'Start',
    stop: 'Stop',
    retry: 'Retry',
    
    // Auth/Registration
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    loginToContinue: 'Log in to continue',
    registerToStart: 'Sign up to get started',
    nameRequired: 'Name is required',
    invalidAge: 'Invalid age',
    invalidWeight: 'Invalid weight',
    myPets: 'My pets',
    epilepsyDiary: 'Epilepsy diary',
    demoDataLabel: 'SIMULATED DATA',
    sensorNoData: 'No data is being received from the sensor.',
    noMeasurementsYet: 'No measurements yet.',
    demoMode: 'Demo mode',
    exitDemoMode: 'Exit demo',
    notes: 'Notes',
    thisMonth: 'This month',
    epilepsySubtitle: 'For dogs and cats with epilepsy: log seizures and share them with your vet',
    epilepsyInfo: 'Log each of {name}\'s seizures with date, duration and intensity. This history helps your vet adjust the treatment.',
    registerSeizure: 'Log seizure',
    totalSeizures: 'Total seizures',
    lastSeizure: 'Last seizure',
    noSeizures: 'No seizures logged. Hopefully it stays that way! Log any episode here.',
    seizureDate: 'Date',
    durationMinutes: 'Duration (minutes)',
    severity: 'Intensity',
    sevMild: 'Mild',
    sevModerate: 'Moderate',
    sevSevere: 'Severe',
    trigger: 'Trigger',
    triggerPlaceholder: 'E.g.: stress, heat, lights...',
    notesPlaceholder: 'Describe what you observed...',
    optional: 'optional',
    invalidDate: 'Invalid date (use YYYY-MM-DD)',
    seizureSaveError: 'Could not save the seizure',
    addPet: 'Add pet',
    addPetSubtitle: 'Tell us about your new pet',
    savePet: 'Save pet',
    petAdded: 'Pet added successfully',
    petAddError: 'Could not save the pet',
    dogNamePlaceholder: 'What is their name?',
    dogSex: 'Sex (optional)',
    male: 'Male',
    female: 'Female',
    emailRequired: 'Email is required',
    invalidEmail: 'Invalid email',
    passwordRequired: 'Password is required',
    minCharacters: 'Minimum 6 characters',
    genericError: 'An error occurred. Please try again.',
    googleLoginError: 'Could not sign in with Google',
    loginButton: 'Log In',
    createAccountButton: 'Create Account',
    orContinueWith: 'or continue with',
    continueWithGoogle: 'Continue with Google',
    noAccount: "Don't have an account? ",
    haveAccount: 'Already have an account? ',
    register: 'Sign up',
    login: 'Log in',
    yourName: 'Your name',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot your password?',
    recoverPassword: 'Recover password',
    enterEmailToRecover: 'Enter your email to receive a recovery code',
    sendCode: 'Send code',
    recoveryCode: 'Recovery code',
    yourCodeIs: 'Your code is',
    codeExpiresIn: 'Expires in 10 minutes',
    enterCode: 'Enter the 6-digit code',
    enterCodeAndPassword: 'Enter the code and your new password',
    code: 'Code',
    newPassword: 'New password',
    changePassword: 'Change password',
    resendCode: 'Resend code',
    passwordUpdated: 'Password updated successfully',
    
    // Navigation
    home: 'Home',
    health: 'Health',
    education: 'Education',
    chat: 'Chat',
    profile: 'Profile',
    
    // Home Screen
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    positiveEducation: 'Positive Education',
    todaySession: "Today's Session",
    homeBannerTitle: 'Analyze and understand your pet\'s health',
    homeBannerSubtitle: 'Upload a photo, a document or describe a symptom and get a clear explanation',
    homeBannerCta: 'Start analysis',
    yourProgress: 'Your Progress',
    quickAccess: 'Quick Access',
    healthActivity: 'Health Activity',
    lastConsultation: 'Last AI consultation',
    lastMedicalEvent: 'Last medical event',
    emotionalState: 'Emotional state',
    noConsultationsYet: 'No consultations yet',
    noEventsYet: 'No events registered',
    notRegisteredToday: 'Not registered today',
    today: 'Today',
    yesterday: 'Yesterday',
    daysAgo: '{n} days ago',
    emotionHappy: 'Happy',
    emotionCalm: 'Calm',
    emotionWorried: 'Worried',
    emotionSad: 'Sad',
    emotionStressed: 'Stressed',
    exerciseLibrary: 'Exercise Library',
    viewAll: 'View all',
    greatJob: 'Great job! You earned',
    bonesToday: 'bones today',
    viewRewards: 'View rewards',
    level: 'Level',
    exercises: 'Exercises',
    practice: 'Practice',
    bones: 'Bones',
    almostLevel: 'Almost at Level',
    days: 'Days',
    nextGoal: 'Next',
    haveQuestions: 'Have questions?',
    askHani: 'Ask Heimdall, canine wellness expert',
    guardianChat: 'Your guardian',
    thePerfectCall: 'The Perfect Recall',
    intermediate: 'Intermediate',
    highPriority: 'HIGH PRIORITY',
    min: 'min',
    explorerLevel: 'Canine Explorer',
    basicSignals: 'Basic Commands',
    sitDownStay: 'Sit, Down, Stay',
    impulseControl: 'Impulse Control',
    waitLeaveRelease: 'Wait, Leave, Drop',
    socialization: 'Socialization',
    dogsPeopleEnvironments: 'Dogs, People, Environments',
    
    // Quick Access
    vest: 'Vest',
    walks: 'Walks',
    uploadAnalysis: 'Upload analysis',
    describeSymptom: 'Describe symptom',
    history: 'History',
    academy: 'Academy',
    pro: 'PRO',
    
    // Health Screen
    health360: 'Health 360°',
    realTimeMonitoring: 'Real-time monitoring',
    heartRate: 'Heart Rate',
    temperature: 'Temperature',
    activity: 'Activity',
    stress: 'Stress',
    bpm: 'bpm',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    normal: 'Normal',
    connectVest: 'Connect Vest',
    vestConnected: 'Vest connected',
    vestDisconnected: 'Vest disconnected',
    medicalHistory: 'Medical History',
    viewMedicalHistory: 'View complete history',
    lastVaccine: 'Last vaccine',
    lastDeworming: 'Last deworming',
    lastVetVisit: 'Last vet visit',
    biometrics: 'Biometrics',
    vitalSigns: 'Vital Signs',
    activityLevel: 'Activity Level',
    stressLevel: 'Stress Level',
    sleeping: 'Sleeping',
    resting: 'Resting',
    active: 'Active',
    veryActive: 'Very Active',
    calm: 'Calm',
    relaxed: 'Relaxed',
    alert: 'Alert',
    anxious: 'Anxious',
    
    // Education Screen
    heimdallAcademy: 'Heimdall Academy',
    heimdallBones: 'Heimdall Bones',
    todaySessionTitle: "Today's Session",
    guidedPrograms: 'Guided Programs',
    basicEducation: 'Basic Education',
    solidFoundations: 'Solid foundations',
    calmControl: 'Calm & Control',
    emotionalManagement: 'Emotional management',
    canineWorld: 'Canine World',
    positiveSocialization: 'Positive socialization',
    puppyStart: 'Puppy Start',
    firstSteps: 'First steps',
    basic: 'Basic',
    emotional: 'Emotional',
    social: 'Social',
    puppies: 'Puppies',
    recommendedGames: 'Recommended Games',
    mentalPuzzle: 'Mental Puzzle',
    tugOfWar: 'Tug of War',
    difficulty: 'Difficulty',
    bond: 'Bond',
    lessons: 'Lessons',
    
    // Chat Screen
    chatWithHani: 'Chat with Hani',
    askAnything: 'Ask anything about your dog',
    typeMessage: 'Type your message...',
    send: 'Send',
    haniGreeting: "Hi! I'm Hani, your canine education assistant. How can I help you today?",
    thinking: 'Thinking...',
    analyzing: 'Analyzing',
    whyDogBarks: 'Why does my dog bark so much?',
    rainyDayGames: 'Games for rainy days',
    howMuchToEat: 'How much should my dog eat?',
    trySaying: 'Try asking:',
    
    // Profile Screen
    myPack: 'My pack',
    invite: 'Invite',
    mainOwner: 'Main owner',
    clinicalFile: 'Clinical File',
    country: 'Country',
    vet: 'Veterinarian',
    allergies: 'Allergies',
    notAssigned: 'Not assigned',
    noneRegistered: 'None registered',
    editClinicalFile: 'Edit clinical file',
    goToPro: 'Go PRO',
    activatePro: 'Activate PRO',
    settings: 'Settings',
    notifications: 'Notifications',
    privacy: 'Privacy and data',
    help: 'Help',

    // Privacy screen
    privacyTitle: 'Privacy and Data',
    dataCollection: 'Data we collect',
    dataCollectionDesc: 'Heimdall collects basic profile data about you and your dog to personalize the experience. This includes name, breed, age, weight and training data.',
    dataStorage: 'Secure storage',
    dataStorageDesc: 'Your data is stored securely on encrypted servers. We use Supabase with AES-256 encryption at rest.',
    dataSharing: 'Do we share your data?',
    dataSharingDesc: 'We do not sell or share your personal data with third parties. We only use information to improve your app experience.',
    aiDataUsage: 'AI data usage',
    aiDataUsageDesc: 'Conversations with Hani are processed through OpenAI. They are not stored on AI servers after processing.',
    deleteAccount: 'Delete my account',
    deleteAccountDesc: 'Deleting your account will permanently remove all your data, including profiles, history and progress.',
    deleteAccountConfirm: 'This action is irreversible. All your data will be permanently deleted.',
    termsOfService: 'Terms of service',
    privacyPolicy: 'Privacy policy',
    lastUpdated: 'Last updated',

    // Help screen
    helpTitle: 'Help Center',
    faq: 'Frequently Asked Questions',
    faqTraining: 'How does training work?',
    faqTrainingAnswer: 'Heimdall offers step-by-step guided training programs. Complete exercises, earn bones and level up while your dog learns.',
    faqPro: 'What does Heimdall PRO include?',
    faqProAnswer: 'PRO unlocks AI video analysis, vet reports, cloud backup and advanced analytics features.',
    faqBluetooth: 'How do I connect the vest?',
    faqBluetoothAnswer: 'Turn on Bluetooth, go to the vest section and tap search devices. Make sure the ESP32 vest is powered on.',
    faqData: 'Is my data safe?',
    faqDataAnswer: 'Yes. We use end-to-end encryption and never share your data with third parties.',
    contactSupport: 'Contact support',
    contactEmail: 'support@heimdall-hani.app',
    reportBug: 'Report a bug',
    rateApp: 'Rate the app',
    rateAppDesc: 'Your feedback helps us improve',
    appVersion: 'App version',

    // PRO screen
    proTitle: 'Heimdall PRO',
    proSubtitle: 'Unlock the full potential of Heimdall',
    alreadyPro: 'You are PRO!',
    enjoyPro: 'Enjoy all Heimdall premium features',
    backToHome: 'Back to home',
    proFeatureVideo: 'AI Video Analysis',
    proFeatureVideoDesc: 'Upload videos of your dog and receive behavior analysis',
    proFeatureReports: 'Vet Reports',
    proFeatureReportsDesc: 'Generate complete reports to share with your vet',
    proFeatureChat: 'Unlimited Chat with Hani',
    proFeatureChatDesc: 'No message limit with your AI assistant',
    proFeatureAnalytics: 'Advanced Analytics',
    proFeatureAnalyticsDesc: 'Detailed health and behavior charts',
    proFeatureCloud: 'Cloud Backup',
    proFeatureCloudDesc: 'All your data safe and synced',
    proFeaturePack: 'Family Pack',
    proFeaturePackDesc: 'Invite up to 5 members to manage your dog',
    allProIncludes: 'Everything included in PRO',
    choosePlan: 'Choose your plan',
    monthly: 'Monthly',
    annual: 'Annual',
    mostPopular: 'MOST POPULAR',
    savingsPercent: 'Save 32%',
    activateProNow: 'Activate PRO Now',
    processing: 'Processing...',
    restorePurchases: 'Restore purchases',
    cancelAnytime: 'Cancel anytime. By subscribing you accept the',
    guarantee7days: '7-day guarantee',
    guaranteeDesc: 'Not satisfied? We refund your money, no questions asked.',
    securePayment: 'Secure payment with',
    loadingPlans: 'Loading plans...',
    language: 'Language',
    logout: 'Log out',
    logoutConfirm: 'Are you sure you want to log out?',
    age: 'Age',
    weight: 'Weight',
    breed: 'Breed',
    editProfile: 'Edit Profile',
    name: 'Name',
    changePhoto: 'Change photo',
    selectLanguage: 'Select Language',
    spanish: 'Español',
    english: 'English',
    italian: 'Italiano',
    years: 'years',
    months: 'months',
    and: 'and',
    chip: 'Chip',
    videoAnalysis: 'Video analysis',
    vetReports: 'Veterinary reports',
    unlimitedChat: 'Unlimited chat with Hani',
    editDogProfile: 'Edit your dog profile',
    dogName: 'Dog name',
    dogAge: 'Age (months)',
    dogWeight: 'Weight (kg)',
    dogBreed: 'Breed',
    chipId: 'Chip number',
    
    // Lessons
    step: 'Step',
    of: 'of',
    complete: 'Complete',
    lessonCompleted: 'Lesson Completed!',
    practicalExercise: 'Your Practical Exercise',
    backToEducation: 'Back to Education',
    proTip: 'Pro Tip',
    whatYouWillLearn: 'What you will learn:',
    commonMistakes: 'Common Mistakes to Avoid:',
    
    // Gamification
    myRewards: 'My Rewards',
    achievements: 'Achievements',
    streak: 'Streak',
    totalBones: 'Total bones',
    levelUp: 'Level Up!',
    newAchievement: 'New Achievement!',
    noAchievements: 'Complete lessons to unlock achievements',
    inviteSent: 'Invitation sent! +5 bones',
    
    // Exercises
    completed: 'completed',
    instructions: 'Instructions:',
    repetitions: 'repetitions',
    exercisesCompleted: 'Exercises Completed!',
    description: 'Description',
    benefits: 'Benefits',
    materials: 'Materials needed',
    
    // Routes
    routes: 'Routes',
    startRoute: 'Start Route',
    stopRoute: 'Stop',
    saveRoute: 'Save Route',
    routeHistory: 'Route History',
    noRoutes: 'No saved routes yet',
    routeSaved: 'Route saved',
    distance: 'Distance',
    duration: 'Duration',
    tracking: 'Tracking',
    walkWithDog: 'Walk with your dog',
    startWalk: 'Start walk',
    endWalk: 'End walk',
    walkCompleted: 'Walk completed!',
    bonesEarned: 'bones earned',
    steps: 'Steps',
    points: 'Points',
    locationPermission: 'Location Permission',
    locationPermissionDesc: 'We need access to your location to track walking routes with your dog',
    grantPermission: 'Grant Permission',
    permissionDenied: 'Permission Denied',
    permissionDeniedDesc: 'Enable location in your device settings',
    hikingTrails: 'Hiking Trails',
    hikingTrailsDesc: 'Recommended walking routes',
    easy: 'Easy',
    moderate: 'Moderate',
    hard: 'Hard',
    dogFriendly: 'Dog-friendly',
    pedometerActive: 'Pedometer active',
    todaySteps: 'Steps today',
    liveTracking: 'Live tracking',
    stopAndSave: 'Stop & Save',
    startWalkWithDog: 'Walk with',
    savedRoutes: 'Saved Routes',
    noRoutesHint: 'Start a walk to save your first route',
    
    // PRO
    proBenefits: 'PRO Benefits',
    monthlyPlan: 'Monthly',
    yearlyPlan: 'Yearly',
    mostPopular: 'MOST POPULAR',
    savingsPercent: 'Save',
    activateNow: 'Activate PRO Now',
    restorePurchases: 'Restore purchases',
    guarantee: '7-day guarantee',
    guaranteeText: "If you're not satisfied, we'll refund your money, no questions asked.",
    alreadyPro: "You're already PRO!",
    enjoyPremium: 'Enjoy all premium features of Heimdall',
    unlockPotential: 'Unlock the full potential of Heimdall',
    everythingIncluded: 'Everything included in PRO',
    choosePlan: 'Choose your plan',
    securePayment: 'Secure payment with',
    month: 'month',
    year: 'year',
    
    // Medical History
    addEvent: 'Add event',
    vaccines: 'Vaccines',
    deworming: 'Deworming',
    vetVisits: 'Vet visits',
    medications: 'Medications',
    surgeries: 'Surgeries',
    other: 'Other',
    noEvents: 'No events registered',
    eventAdded: 'Event added',
    eventDeleted: 'Event deleted',
    eventType: 'Event type',
    eventDate: 'Date',
    eventDescription: 'Description',
    
    // Vest/Bluetooth
    smartVest: 'Smart Vest',
    connectDevice: 'Connect device',
    disconnectDevice: 'Disconnect',
    searching: 'Searching...',
    connected: 'Connected',
    disconnected: 'Disconnected',
    batteryLevel: 'Battery level',
    lastSync: 'Last sync',
    syncNow: 'Sync now',
    deviceNotFound: 'Device not found',
    bluetoothOff: 'Bluetooth is off',
    enableBluetooth: 'Enable Bluetooth to continue',
    simulatorMode: 'Simulator Mode',
    simulatorDescription: 'Using simulated data for demonstration',
    
    // Onboarding
    nowWatching: 'Heimdall is now watching',
    yourDog: 'your dog',
    configuredDescription: 'We have configured everything so you can monitor the health and well-being of your furry companion.',
    personalizedAI: 'Personalized AI assistant',
    goToHome: 'Go to home',
    
    // Google Wallet
    digitalIdCard: 'Digital ID Card',
    addToGoogleWallet: 'Add to Google Wallet',
    walletCardDescription: 'Carry your dog\'s ID with you always in Google Wallet',
    
    // Bluetooth/ESP32
    scanForDevices: 'Scan for devices',
    stopScanning: 'Stop scanning',
    noDevicesFound: 'No devices found',
    connectingTo: 'Connecting to',
    esp32Device: 'ESP32 Device',
    heimdallVest: 'Heimdall Vest',
    signalStrength: 'Signal strength',
    availableDevices: 'Available devices',
    useSimulator: 'Use simulator',
    realDevice: 'Real device',
    disconnectConfirm: 'Are you sure you want to disconnect the vest?',
    
    // Leaderboard
    leaderboard: 'Ranking',
    leaderboardTitle: 'Pack Ranking',
    topTrainers: 'Top Trainers',
    yourPosition: 'Your position',
    noRankYet: 'Complete lessons to appear',
    rank: 'Rank',
    viewLeaderboard: 'View ranking',
    
    // Weekly Summary
    weeklyProgress: 'Weekly Progress',
    thisWeek: 'This week',
    bonesThisWeek: 'Bones',
    exercisesThisWeek: 'Activities',
    xpThisWeek: 'XP earned',
    streakActive: 'Active streak',
    keepItUp: 'Keep it up!',
    startTraining: 'Start training this week!',
    weeklyGoal: 'Weekly goal',
    daysActive: 'Days active',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    theme: 'Theme',
    appearance: 'Appearance',

    // Health vest banner
    vestComingSoon: 'Coming soon with the Vest Pack',
    vestComingSoonDesc: 'The metrics you see are examples. Connect the Heimdall ESP32 vest to monitor your dog in real time.',
    vestGetPack: 'Discover Vest Pack',
    demoData: 'Sample data',
    howDoYouFeel: 'How are you feeling today?',
    startEmotionDiary: 'Start emotional diary',
    todayYouFeel: 'Today you feel...',
    addNotePlaceholder: 'Add a note (optional)...',
    saving: 'Saving...',
    update: 'Update',
    weeklyInsight: 'Weekly Insight',
    analyzingWeek: 'Analyzing your week...',
    dominantEmotion: 'Dominant emotion:',
    diaryEmpty: 'Start your diary by recording how you feel today. Heimdall will analyze your emotions every week.',
    diaryError: 'Could not save the entry',
    emotionHappy: 'Happy',
    emotionCalm: 'Calm',
    emotionWorried: 'Worried',
    emotionSad: 'Sad',
    emotionStressed: 'Stressed',
    // What does Heimdall do
    whatDoesHeimdall: 'What does Heimdall do?',
    heimdallFeature1: 'Understands your pet\'s health',
    heimdallFeature2: 'Detects risks early',
    heimdallFeature3: 'Make decisions with clarity',
  },
  it: {
    // General
    loading: 'Caricamento...',
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    edit: 'Modifica',
    confirm: 'Conferma',
    back: 'Indietro',
    next: 'Avanti',
    previous: 'Precedente',
    done: 'Fatto',
    error: 'Errore',
    success: 'Successo',
    close: 'Chiudi',
    start: 'Inizia',
    stop: 'Ferma',
    retry: 'Riprova',
    
    // Auth/Registration
    welcomeBack: 'Bentornato',
    createAccount: 'Crea account',
    loginToContinue: 'Accedi per continuare',
    registerToStart: 'Registrati per iniziare',
    nameRequired: 'Il nome è obbligatorio',
    invalidAge: 'Età non valida',
    invalidWeight: 'Peso non valido',
    myPets: 'I miei animali',
    epilepsyDiary: 'Diario dell\'epilessia',
    demoDataLabel: 'DATI SIMULATI',
    sensorNoData: 'Non si stanno ricevendo dati dal sensore.',
    noMeasurementsYet: 'Ancora nessuna misurazione.',
    demoMode: 'Modalità demo',
    exitDemoMode: 'Esci dalla demo',
    notes: 'Note',
    thisMonth: 'Questo mese',
    epilepsySubtitle: 'Per cani e gatti con epilessia: registra le crisi e condividile con il veterinario',
    epilepsyInfo: 'Registra ogni crisi di {name} con data, durata e intensità. Questo storico aiuta il veterinario ad adattare il trattamento.',
    registerSeizure: 'Registra crisi',
    totalSeizures: 'Crisi totali',
    lastSeizure: 'Ultima crisi',
    noSeizures: 'Nessuna crisi registrata. Speriamo continui così! Registra qui qualsiasi episodio.',
    seizureDate: 'Data',
    durationMinutes: 'Durata (minuti)',
    severity: 'Intensità',
    sevMild: 'Lieve',
    sevModerate: 'Moderata',
    sevSevere: 'Grave',
    trigger: 'Fattore scatenante',
    triggerPlaceholder: 'Es: stress, caldo, luci...',
    notesPlaceholder: 'Descrivi cosa hai osservato...',
    optional: 'opzionale',
    invalidDate: 'Data non valida (usa YYYY-MM-DD)',
    seizureSaveError: 'Impossibile salvare la crisi',
    addPet: 'Aggiungi animale',
    addPetSubtitle: 'Raccontaci del tuo nuovo animale',
    savePet: 'Salva animale',
    petAdded: 'Animale aggiunto correttamente',
    petAddError: 'Impossibile salvare l\'animale',
    dogNamePlaceholder: 'Come si chiama?',
    dogSex: 'Sesso (opzionale)',
    male: 'Maschio',
    female: 'Femmina',
    emailRequired: "L'email è obbligatoria",
    invalidEmail: 'Email non valida',
    passwordRequired: 'La password è obbligatoria',
    minCharacters: 'Minimo 6 caratteri',
    genericError: 'Si è verificato un errore. Riprova.',
    googleLoginError: 'Impossibile accedere con Google',
    loginButton: 'Accedi',
    createAccountButton: 'Crea Account',
    orContinueWith: 'o continua con',
    continueWithGoogle: 'Continua con Google',
    noAccount: 'Non hai un account? ',
    haveAccount: 'Hai già un account? ',
    register: 'Registrati',
    login: 'Accedi',
    yourName: 'Il tuo nome',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Hai dimenticato la password?',
    recoverPassword: 'Recupera password',
    enterEmailToRecover: 'Inserisci la tua email per ricevere un codice di recupero',
    sendCode: 'Invia codice',
    recoveryCode: 'Codice di recupero',
    yourCodeIs: 'Il tuo codice è',
    codeExpiresIn: 'Scade tra 10 minuti',
    enterCode: 'Inserisci il codice a 6 cifre',
    enterCodeAndPassword: 'Inserisci il codice e la tua nuova password',
    code: 'Codice',
    newPassword: 'Nuova password',
    changePassword: 'Cambia password',
    resendCode: 'Reinvia codice',
    passwordUpdated: 'Password aggiornata con successo',
    
    // Navigation
    home: 'Home',
    health: 'Salute',
    education: 'Educazione',
    chat: 'Chat',
    profile: 'Profilo',
    
    // Home Screen
    goodMorning: 'Buongiorno',
    goodAfternoon: 'Buon pomeriggio',
    goodEvening: 'Buonasera',
    positiveEducation: 'Educazione Positiva',
    todaySession: 'Sessione di Oggi',
    homeBannerTitle: 'Analizza e comprendi la salute del tuo animale',
    homeBannerSubtitle: 'Carica una foto, un documento o descrivi un sintomo e ottieni una spiegazione chiara',
    homeBannerCta: 'Inizia analisi',
    yourProgress: 'I Tuoi Progressi',
    quickAccess: 'Accesso Rapido',
    healthActivity: 'Attivita di salute',
    lastConsultation: 'Ultima consulta IA',
    lastMedicalEvent: 'Ultimo evento medico',
    emotionalState: 'Stato emotivo',
    noConsultationsYet: 'Nessuna consulta ancora',
    noEventsYet: 'Nessun evento registrato',
    notRegisteredToday: 'Non registrato oggi',
    today: 'Oggi',
    yesterday: 'Ieri',
    daysAgo: '{n} giorni fa',
    emotionHappy: 'Felice',
    emotionCalm: 'Tranquillo',
    emotionWorried: 'Preoccupato',
    emotionSad: 'Triste',
    emotionStressed: 'Stressato',
    exerciseLibrary: 'Libreria Esercizi',
    viewAll: 'Vedi tutto',
    greatJob: 'Ottimo lavoro! Hai guadagnato',
    bonesToday: 'ossa oggi',
    viewRewards: 'Vedi premi',
    level: 'Livello',
    exercises: 'Esercizi',
    practice: 'Pratica',
    bones: 'Ossa',
    almostLevel: 'Quasi al Livello',
    days: 'Giorni',
    nextGoal: 'Prossimo',
    haveQuestions: 'Hai domande?',
    askHani: 'Chiedi a Heimdall, esperto di benessere canino',
    guardianChat: 'Il tuo guardiano',
    thePerfectCall: 'Il Richiamo Perfetto',
    intermediate: 'Intermedio',
    highPriority: 'PRIORITÀ ALTA',
    min: 'min',
    explorerLevel: 'Esploratore Canino',
    basicSignals: 'Comandi Base',
    sitDownStay: 'Seduto, Terra, Fermo',
    impulseControl: 'Controllo degli Impulsi',
    waitLeaveRelease: 'Aspetta, Lascia, Molla',
    socialization: 'Socializzazione',
    dogsPeopleEnvironments: 'Cani, Persone, Ambienti',
    
    // Quick Access
    vest: 'Gilet',
    walks: 'Passeggiate',
    uploadAnalysis: 'Carica analisi',
    describeSymptom: 'Descrivi sintomo',
    history: 'Cronologia',
    academy: 'Accademia',
    pro: 'PRO',
    
    // Health Screen
    health360: 'Salute 360°',
    realTimeMonitoring: 'Monitoraggio in tempo reale',
    heartRate: 'Frequenza Cardiaca',
    temperature: 'Temperatura',
    activity: 'Attività',
    stress: 'Stress',
    bpm: 'bpm',
    high: 'Alta',
    medium: 'Media',
    low: 'Basso',
    normal: 'Normale',
    connectVest: 'Connetti Gilet',
    vestConnected: 'Gilet connesso',
    vestDisconnected: 'Gilet disconnesso',
    medicalHistory: 'Cartella Clinica',
    viewMedicalHistory: 'Vedi cartella completa',
    lastVaccine: 'Ultimo vaccino',
    lastDeworming: 'Ultima sverminazione',
    lastVetVisit: 'Ultima visita veterinaria',
    biometrics: 'Biometrici',
    vitalSigns: 'Segni Vitali',
    activityLevel: 'Livello di Attività',
    stressLevel: 'Livello di Stress',
    sleeping: 'Dormendo',
    resting: 'Riposando',
    active: 'Attivo',
    veryActive: 'Molto Attivo',
    calm: 'Calmo',
    relaxed: 'Rilassato',
    alert: 'Allerta',
    anxious: 'Ansioso',
    
    // Education Screen
    heimdallAcademy: 'Accademia Heimdall',
    heimdallBones: 'Ossa Heimdall',
    todaySessionTitle: 'Sessione di Oggi',
    guidedPrograms: 'Programmi Guidati',
    basicEducation: 'Educazione Base',
    solidFoundations: 'Basi solide',
    calmControl: 'Calma e Controllo',
    emotionalManagement: 'Gestione emotiva',
    canineWorld: 'Mondo Canino',
    positiveSocialization: 'Socializzazione positiva',
    puppyStart: 'Inizio Cucciolo',
    firstSteps: 'Primi passi',
    basic: 'Base',
    emotional: 'Emotivo',
    social: 'Sociale',
    puppies: 'Cuccioli',
    recommendedGames: 'Giochi Consigliati',
    mentalPuzzle: 'Puzzle Mentale',
    tugOfWar: 'Tiro alla Fune',
    difficulty: 'Difficoltà',
    bond: 'Legame',
    lessons: 'Lezioni',
    
    // Chat Screen
    chatWithHani: 'Chat con Hani',
    askAnything: 'Chiedi qualsiasi cosa sul tuo cane',
    typeMessage: 'Scrivi il tuo messaggio...',
    send: 'Invia',
    haniGreeting: 'Ciao! Sono Hani, il tuo assistente per l\'educazione canina. Come posso aiutarti oggi?',
    thinking: 'Sto pensando...',
    analyzing: 'Analizzando',
    whyDogBarks: 'Perché il mio cane abbaia così tanto?',
    rainyDayGames: 'Giochi per i giorni di pioggia',
    howMuchToEat: 'Quanto dovrebbe mangiare il mio cane?',
    trySaying: 'Prova a chiedere:',
    
    // Profile Screen
    myPack: 'Il mio branco',
    invite: 'Invita',
    mainOwner: 'Proprietario principale',
    clinicalFile: 'Scheda Clinica',
    country: 'Paese',
    vet: 'Veterinario',
    allergies: 'Allergie',
    notAssigned: 'Non assegnato',
    noneRegistered: 'Nessuna registrata',
    editClinicalFile: 'Modifica scheda clinica',
    goToPro: 'Passa a PRO',
    activatePro: 'Attiva PRO',
    settings: 'Impostazioni',
    notifications: 'Notifiche',
    privacy: 'Privacy e dati',
    help: 'Aiuto',

    // Privacy screen
    privacyTitle: 'Privacy e Dati',
    dataCollection: 'Dati che raccogliamo',
    dataCollectionDesc: 'Heimdall raccoglie dati base del tuo profilo e del tuo cane per personalizzare l\'esperienza. Include nome, razza, eta, peso e dati di addestramento.',
    dataStorage: 'Archiviazione sicura',
    dataStorageDesc: 'I tuoi dati sono archiviati in modo sicuro su server crittografati. Utilizziamo Supabase con crittografia AES-256.',
    dataSharing: 'Condividiamo i tuoi dati?',
    dataSharingDesc: 'Non vendiamo ne condividiamo i tuoi dati personali con terze parti. Usiamo le informazioni solo per migliorare la tua esperienza.',
    aiDataUsage: 'Uso dei dati nell\'IA',
    aiDataUsageDesc: 'Le conversazioni con Hani sono elaborate tramite OpenAI. Non vengono memorizzate sui server IA dopo l\'elaborazione.',
    deleteAccount: 'Elimina il mio account',
    deleteAccountDesc: 'L\'eliminazione del tuo account cancellera permanentemente tutti i tuoi dati, inclusi profili, cronologia e progressi.',
    deleteAccountConfirm: 'Questa azione e irreversibile. Tutti i tuoi dati saranno eliminati permanentemente.',
    termsOfService: 'Termini di servizio',
    privacyPolicy: 'Informativa sulla privacy',
    lastUpdated: 'Ultimo aggiornamento',

    // Help screen
    helpTitle: 'Centro Assistenza',
    faq: 'Domande Frequenti',
    faqTraining: 'Come funziona l\'addestramento?',
    faqTrainingAnswer: 'Heimdall offre programmi di addestramento guidati passo dopo passo. Completa esercizi, guadagna ossa e sali di livello mentre il tuo cane impara.',
    faqPro: 'Cosa include Heimdall PRO?',
    faqProAnswer: 'PRO sblocca analisi video IA, rapporti veterinari, backup cloud e funzioni avanzate di analisi.',
    faqBluetooth: 'Come collego il gilet?',
    faqBluetoothAnswer: 'Attiva il Bluetooth, vai alla sezione gilet e tocca cerca dispositivi. Assicurati che il gilet ESP32 sia acceso.',
    faqData: 'I miei dati sono al sicuro?',
    faqDataAnswer: 'Si. Usiamo la crittografia end-to-end e non condividiamo mai i tuoi dati con terze parti.',
    contactSupport: 'Contatta il supporto',
    contactEmail: 'supporto@heimdall-hani.app',
    reportBug: 'Segnala un errore',
    rateApp: 'Valuta l\'app',
    rateAppDesc: 'La tua opinione ci aiuta a migliorare',
    appVersion: 'Versione dell\'app',

    // PRO screen
    proTitle: 'Heimdall PRO',
    proSubtitle: 'Sblocca tutto il potenziale di Heimdall',
    alreadyPro: 'Sei gia PRO!',
    enjoyPro: 'Goditi tutte le funzioni premium di Heimdall',
    backToHome: 'Torna alla home',
    proFeatureVideo: 'Analisi Video IA',
    proFeatureVideoDesc: 'Carica video del tuo cane e ricevi analisi comportamentali',
    proFeatureReports: 'Rapporti Veterinari',
    proFeatureReportsDesc: 'Genera rapporti completi da condividere con il tuo veterinario',
    proFeatureChat: 'Chat Illimitata con Hani',
    proFeatureChatDesc: 'Senza limite di messaggi con il tuo assistente IA',
    proFeatureAnalytics: 'Analisi Avanzate',
    proFeatureAnalyticsDesc: 'Grafici dettagliati di salute e comportamento',
    proFeatureCloud: 'Backup Cloud',
    proFeatureCloudDesc: 'Tutti i tuoi dati sicuri e sincronizzati',
    proFeaturePack: 'Branco Familiare',
    proFeaturePackDesc: 'Invita fino a 5 membri per gestire il tuo cane',
    allProIncludes: 'Tutto incluso in PRO',
    choosePlan: 'Scegli il tuo piano',
    monthly: 'Mensile',
    annual: 'Annuale',
    mostPopular: 'PIU POPOLARE',
    savingsPercent: 'Risparmia 32%',
    activateProNow: 'Attiva PRO Adesso',
    processing: 'Elaborazione...',
    restorePurchases: 'Ripristina acquisti',
    cancelAnytime: 'Cancella quando vuoi. Abbonandoti accetti i',
    guarantee7days: 'Garanzia 7 giorni',
    guaranteeDesc: 'Non soddisfatto? Ti rimborsiamo senza domande.',
    securePayment: 'Pagamento sicuro con',
    loadingPlans: 'Caricamento piani...',
    language: 'Lingua',
    logout: 'Esci',
    logoutConfirm: 'Sei sicuro di voler uscire?',
    age: 'Età',
    weight: 'Peso',
    breed: 'Razza',
    editProfile: 'Modifica Profilo',
    name: 'Nome',
    changePhoto: 'Cambia foto',
    selectLanguage: 'Seleziona Lingua',
    spanish: 'Español',
    english: 'English',
    italian: 'Italiano',
    years: 'anni',
    months: 'mesi',
    and: 'e',
    chip: 'Chip',
    videoAnalysis: 'Analisi video',
    vetReports: 'Referti veterinari',
    unlimitedChat: 'Chat illimitata con Hani',
    editDogProfile: 'Modifica il profilo del tuo cane',
    dogName: 'Nome del cane',
    dogAge: 'Età (mesi)',
    dogWeight: 'Peso (kg)',
    dogBreed: 'Razza',
    chipId: 'Numero chip',
    
    // Lessons
    step: 'Passo',
    of: 'di',
    complete: 'Completa',
    lessonCompleted: 'Lezione Completata!',
    practicalExercise: 'Il Tuo Esercizio Pratico',
    backToEducation: 'Torna all\'Educazione',
    proTip: 'Consiglio Pro',
    whatYouWillLearn: 'Cosa imparerai:',
    commonMistakes: 'Errori Comuni da Evitare:',
    
    // Gamification
    myRewards: 'Le Mie Ricompense',
    achievements: 'Traguardi',
    streak: 'Serie',
    totalBones: 'Ossa totali',
    levelUp: 'Livello Su!',
    newAchievement: 'Nuovo Traguardo!',
    noAchievements: 'Completa le lezioni per sbloccare i traguardi',
    inviteSent: 'Invito inviato! +5 ossa',
    
    // Exercises
    completed: 'completati',
    instructions: 'Istruzioni:',
    repetitions: 'ripetizioni',
    exercisesCompleted: 'Esercizi Completati!',
    description: 'Descrizione',
    benefits: 'Benefici',
    materials: 'Materiali necessari',
    
    // Routes
    routes: 'Percorsi',
    startRoute: 'Inizia Percorso',
    stopRoute: 'Ferma',
    saveRoute: 'Salva Percorso',
    routeHistory: 'Cronologia Percorsi',
    noRoutes: 'Ancora nessun percorso salvato',
    routeSaved: 'Percorso salvato',
    distance: 'Distanza',
    duration: 'Durata',
    tracking: 'Tracciamento',
    walkWithDog: 'Passeggia con il tuo cane',
    startWalk: 'Inizia passeggiata',
    endWalk: 'Termina passeggiata',
    walkCompleted: 'Passeggiata completata!',
    bonesEarned: 'ossa guadagnate',
    steps: 'Passi',
    points: 'Punti',
    locationPermission: 'Permesso di posizione',
    locationPermissionDesc: 'Abbiamo bisogno della tua posizione per tracciare i percorsi con il tuo cane',
    grantPermission: 'Concedi permesso',
    permissionDenied: 'Permesso negato',
    permissionDeniedDesc: 'Attiva la posizione nelle impostazioni del dispositivo',
    hikingTrails: 'Sentieri escursionistici',
    hikingTrailsDesc: 'Percorsi consigliati per passeggiate',
    easy: 'Facile',
    moderate: 'Moderata',
    hard: 'Difficile',
    dogFriendly: 'Dog-friendly',
    pedometerActive: 'Contapassi attivo',
    todaySteps: 'Passi oggi',
    liveTracking: 'Tracciamento in tempo reale',
    stopAndSave: 'Ferma e Salva',
    startWalkWithDog: 'Passeggia con',
    savedRoutes: 'Percorsi salvati',
    noRoutesHint: 'Inizia una passeggiata per salvare il tuo primo percorso',
    
    // PRO
    proBenefits: 'Benefici PRO',
    monthlyPlan: 'Mensile',
    yearlyPlan: 'Annuale',
    mostPopular: 'PIÙ POPOLARE',
    savingsPercent: 'Risparmia',
    activateNow: 'Attiva PRO Ora',
    restorePurchases: 'Ripristina acquisti',
    guarantee: 'Garanzia di 7 giorni',
    guaranteeText: 'Se non sei soddisfatto, ti rimborsiamo senza domande.',
    alreadyPro: 'Sei già PRO!',
    enjoyPremium: 'Goditi tutte le funzioni premium di Heimdall',
    unlockPotential: 'Sblocca tutto il potenziale di Heimdall',
    everythingIncluded: 'Tutto incluso in PRO',
    choosePlan: 'Scegli il tuo piano',
    securePayment: 'Pagamento sicuro con',
    month: 'mese',
    year: 'anno',
    
    // Medical History
    addEvent: 'Aggiungi evento',
    vaccines: 'Vaccini',
    deworming: 'Sverminazione',
    vetVisits: 'Visite veterinarie',
    medications: 'Farmaci',
    surgeries: 'Interventi',
    other: 'Altri',
    noEvents: 'Nessun evento registrato',
    eventAdded: 'Evento aggiunto',
    eventDeleted: 'Evento eliminato',
    eventType: 'Tipo di evento',
    eventDate: 'Data',
    eventDescription: 'Descrizione',
    
    // Vest/Bluetooth
    smartVest: 'Gilet Intelligente',
    connectDevice: 'Connetti dispositivo',
    disconnectDevice: 'Disconnetti',
    searching: 'Ricerca...',
    connected: 'Connesso',
    disconnected: 'Disconnesso',
    batteryLevel: 'Livello batteria',
    lastSync: 'Ultima sincronizzazione',
    syncNow: 'Sincronizza ora',
    deviceNotFound: 'Dispositivo non trovato',
    bluetoothOff: 'Bluetooth disattivato',
    enableBluetooth: 'Attiva Bluetooth per continuare',
    simulatorMode: 'Modalità Simulatore',
    simulatorDescription: 'Utilizzo dati simulati per la dimostrazione',
    
    // Onboarding
    nowWatching: 'Heimdall ora sorveglia',
    yourDog: 'il tuo cane',
    configuredDescription: 'Abbiamo configurato tutto in modo che tu possa monitorare la salute e il benessere del tuo amico peloso.',
    personalizedAI: 'Assistente IA personalizzato',
    goToHome: 'Vai alla home',
    
    // Google Wallet
    digitalIdCard: 'Carta d\'identità digitale',
    addToGoogleWallet: 'Aggiungi a Google Wallet',
    walletCardDescription: 'Porta sempre con te l\'identificazione del tuo cane in Google Wallet',
    
    // Bluetooth/ESP32
    scanForDevices: 'Cerca dispositivi',
    stopScanning: 'Ferma ricerca',
    noDevicesFound: 'Nessun dispositivo trovato',
    connectingTo: 'Connessione a',
    esp32Device: 'Dispositivo ESP32',
    heimdallVest: 'Gilet Heimdall',
    signalStrength: 'Potenza del segnale',
    availableDevices: 'Dispositivi disponibili',
    useSimulator: 'Usa simulatore',
    realDevice: 'Dispositivo reale',
    disconnectConfirm: 'Sei sicuro di voler disconnettere il gilet?',
    
    // Leaderboard
    leaderboard: 'Classifica',
    leaderboardTitle: 'Classifica del Branco',
    topTrainers: 'Migliori Addestratori',
    yourPosition: 'La tua posizione',
    noRankYet: 'Completa lezioni per apparire',
    rank: 'Posizione',
    viewLeaderboard: 'Vedi classifica',
    
    // Weekly Summary
    weeklyProgress: 'Progresso Settimanale',
    thisWeek: 'Questa settimana',
    bonesThisWeek: 'Ossa',
    exercisesThisWeek: 'Attivit\u00e0',
    xpThisWeek: 'XP guadagnato',
    streakActive: 'Serie attiva',
    keepItUp: 'Continua cos\u00ec!',
    startTraining: 'Inizia ad allenarti questa settimana!',
    weeklyGoal: 'Obiettivo settimanale',
    daysActive: 'Giorni attivi',
    darkMode: 'Modalit\u00e0 scura',
    lightMode: 'Modalit\u00e0 chiara',
    theme: 'Tema',
    appearance: 'Aspetto',

    // Health vest banner
    vestComingSoon: 'Prossimamente con il Pack Gilet',
    vestComingSoonDesc: 'Le metriche che vedi sono di esempio. Collega il gilet Heimdall ESP32 per monitorare il tuo cane in tempo reale.',
    vestGetPack: 'Scopri Pack Gilet',
    demoData: 'Dati di esempio',
    howDoYouFeel: 'Come vi sentite oggi?',
    startEmotionDiary: 'Inizia il diario emotivo',
    todayYouFeel: 'Oggi ti senti...',
    addNotePlaceholder: 'Aggiungi una nota (opzionale)...',
    saving: 'Salvataggio...',
    update: 'Aggiorna',
    weeklyInsight: 'Insight Settimanale',
    analyzingWeek: 'Analizzando la tua settimana...',
    dominantEmotion: 'Emozione predominante:',
    diaryEmpty: 'Inizia il tuo diario registrando come vi sentite oggi. Heimdall analizzerà le tue emozioni ogni settimana.',
    diaryError: 'Impossibile salvare la voce',
    emotionHappy: 'Felice',
    emotionCalm: 'Calmo',
    emotionWorried: 'Preoccupato',
    emotionSad: 'Triste',
    emotionStressed: 'Stressato',
    // What does Heimdall do
    whatDoesHeimdall: 'Cosa fa Heimdall?',
    heimdallFeature1: 'Comprende la salute del tuo animale',
    heimdallFeature2: 'Rileva i rischi in tempo',
    heimdallFeature3: 'Prendi decisioni con chiarezza',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLang = await SecureStore.getItemAsync('app_language');
      if (savedLang && (savedLang === 'es' || savedLang === 'en' || savedLang === 'it')) {
        setLanguageState(savedLang);
      }
    } catch (error) {
      console.log('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await SecureStore.setItemAsync('app_language', lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Helper to get language name for AI
export function getLanguageName(lang: Language): string {
  switch (lang) {
    case 'es': return 'Spanish';
    case 'en': return 'English';
    case 'it': return 'Italian';
  }
}
